### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by SkipList1** [ChouBaoDxs/lagou2markdown#1]
2021-03-13 23:20:27,352 - <ipython-input-5-b04a369c3048>[line:131] -   ERROR: {'course_id': 5, 'e': "OSError(22, 'Invalid argument')", 'traceback': 'Traceback (most recent call last):\n  File "<ipython-input-5-b04a369c3048>", line 123, in main\n    self.deal_a_course(course_id)\n  File "<ipython-input-5-b04a369c3048>", line 116, in deal_a_course\n    self.save_markdown(lesson_md_file_path, lesson_img_dir, md_relative_img_dir, text_content_html)\n  File "<ipython-input-5-b04a369c3048>", line 74, in save_markdown\n    with open(md_file_path, \'w\', encoding=\'utf8\') as f:\nOSError: [Errno 22] Invalid argument

**Comment by SkipList1** [comment]
2021-03-13 23:16:51,386 - <ipython-input-3-b04a369c3048>[line:131] -   ERROR: {'course_id': 612, 'e': 'AttributeError("\'NoneType\' object has no attribute \'replace\'")', 'traceback': 'Traceback (most recent call last):\n  File "<ipython-input-3-b04a369c3048>", line 123, in main\n    self.deal_a_course(course_id)\n  File "<ipython-input-3-b04a369c3048>", line 116, in deal_a_course\n    self.save_markdown(lesson_md_file_path, lesson_img_dir, md_relative_img_dir, text_content_html)\n  File "<ipython-input-3-b04a369c3048>", line 56, in save_markdown\n    markdown_str = html2text.html2text(markdown_html_str)\n
